/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */

/*
The purpose of this class is to create a purchase window where the calculations for
purchasing tickets takes place. and a receipt is written.
 */
public class Purchase extends javax.swing.JFrame {

    String movName;
    String movDate;

    /**
     * Creates new form Purchase
     */
    public Purchase(String name, String date) {
        movName = name;
        movDate = date;
        initComponents();
        this.setLocationRelativeTo(null);//!Centers the window.
        movieDetailsTF.setText("The movie you have selected is:\n" + movName
                + "\n and your chosen date and time is: \n" + movDate);
    }

    private Purchase() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchasePanel = new javax.swing.JPanel();
        movieDataLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        studentLabel = new javax.swing.JLabel();
        adultLabel = new javax.swing.JLabel();
        seniorLabel = new javax.swing.JLabel();
        studentPriceLabel = new javax.swing.JLabel();
        adultPriceLabel = new javax.swing.JLabel();
        seniorPriceLabel = new javax.swing.JLabel();
        studentQty = new javax.swing.JComboBox<>();
        adultQty = new javax.swing.JComboBox<>();
        seniorQty = new javax.swing.JComboBox<>();
        subTotalLabel = new javax.swing.JLabel();
        studentSubTotal = new javax.swing.JTextField();
        adultSubTotal = new javax.swing.JTextField();
        seniorSubTotal = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalPriceTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieDetailsTF = new javax.swing.JTextArea();
        btnPurchase = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Purchase");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(0, 0));

        movieDataLabel.setText("Movie Selection Information");

        typeLabel.setText("Type");

        PriceLabel.setText("Price");

        quantityLabel.setText("Quantity");

        studentLabel.setText("Student");

        adultLabel.setText("Adult");

        seniorLabel.setText("Senior");

        studentPriceLabel.setText("£8.80");

        adultPriceLabel.setText("£11.50");

        seniorPriceLabel.setText("£8.60");

        studentQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        studentQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentQtyActionPerformed(evt);
            }
        });

        adultQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        adultQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultQtyActionPerformed(evt);
            }
        });

        seniorQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        seniorQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorQtyActionPerformed(evt);
            }
        });

        subTotalLabel.setText("Sub Total (£)");

        studentSubTotal.setEditable(false);
        studentSubTotal.setText("£0.00");
        studentSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSubTotalActionPerformed(evt);
            }
        });

        adultSubTotal.setEditable(false);
        adultSubTotal.setText("£0.00");
        adultSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultSubTotalActionPerformed(evt);
            }
        });

        seniorSubTotal.setEditable(false);
        seniorSubTotal.setText("£0.00");

        totalLabel.setText("TOTAL PRICE:");

        totalPriceTextField.setEditable(false);
        totalPriceTextField.setText("£0.00");
        totalPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceTextFieldActionPerformed(evt);
            }
        });

        movieDetailsTF.setEditable(false);
        movieDetailsTF.setColumns(20);
        movieDetailsTF.setRows(5);
        jScrollPane1.setViewportView(movieDetailsTF);

        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
        purchasePanel.setLayout(purchasePanelLayout);
        purchasePanelLayout.setHorizontalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adultLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seniorLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addComponent(movieDataLabel)
                        .addGap(108, 108, 108)
                        .addComponent(typeLabel)))
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(purchasePanelLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(purchasePanelLayout.createSequentialGroup()
                                            .addComponent(seniorPriceLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(seniorQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(purchasePanelLayout.createSequentialGroup()
                                            .addComponent(adultPriceLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(adultQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(purchasePanelLayout.createSequentialGroup()
                                            .addComponent(studentPriceLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(studentQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasePanelLayout.createSequentialGroup()
                                            .addComponent(PriceLabel)
                                            .addGap(56, 56, 56)
                                            .addComponent(quantityLabel))))
                                .addGroup(purchasePanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(purchasePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(totalLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(seniorSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(adultSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(studentSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(subTotalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(totalPriceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        purchasePanelLayout.setVerticalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieDataLabel)
                    .addComponent(typeLabel)
                    .addComponent(PriceLabel)
                    .addComponent(quantityLabel)
                    .addComponent(subTotalLabel))
                .addGap(29, 29, 29)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentLabel)
                            .addComponent(studentPriceLabel)
                            .addComponent(studentQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adultLabel)
                            .addComponent(adultPriceLabel)
                            .addComponent(adultQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adultSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seniorLabel)
                            .addComponent(seniorPriceLabel)
                            .addComponent(seniorQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seniorSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(totalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBtn))
                        .addGap(50, 50, 50)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPurchase)
                            .addComponent(btnExit)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void studentSubTotal() { //calculates the student subtotal
        
        double price;
        double qty;
        double stuSubTotal;

        qty = studentQty.getSelectedIndex();
        price = 8.80;           
        stuSubTotal = price * qty;
        NumberFormat gbp = NumberFormat.getCurrencyInstance(Locale.UK);
        String stuStrTotal = String.valueOf(gbp.format(stuSubTotal));
        studentSubTotal.setText(stuStrTotal);
        totalPrice();
    }

    private void adultSubTotal() {//calculates adult subtotal
        double price = 11.50;
        double qty = adultQty.getSelectedIndex();
        double adSubTotal = price * qty;
        NumberFormat gbp = NumberFormat.getCurrencyInstance(Locale.UK);
        String adultStrTotal = String.valueOf(gbp.format(adSubTotal));
        adultSubTotal.setText(adultStrTotal);
        totalPrice();
    }

    private void seniorSubTotal() {//calculates senior subtotal.
        double price = 8.60;
        double qty = seniorQty.getSelectedIndex();
        double senSubTotal = price * qty;
        NumberFormat gbp = NumberFormat.getCurrencyInstance(Locale.UK);
        String seniorStrTotal = String.valueOf(gbp.format(senSubTotal));
        seniorSubTotal.setText(seniorStrTotal);
        totalPrice();
    }

    private void totalPrice() {//add try and catch to there.
        double totalPrice;
        
        String stu = studentSubTotal.getText();
        stu = stu.substring(1);
        double stuTotal = Double.parseDouble(stu);

        String adult = adultSubTotal.getText();
        adult = adult.substring(1);
        double adultTotal = Double.parseDouble(adult);

        String senior = seniorSubTotal.getText();
        senior = senior.substring(1);
        double seniorTotal = Double.parseDouble(senior);

        totalPrice = stuTotal + adultTotal + seniorTotal;
        NumberFormat gbp = NumberFormat.getCurrencyInstance(Locale.UK);
        String totalStr = String.valueOf(gbp.format(totalPrice));
        totalPriceTextField.setText(totalStr);

    }

    private void writeReceipt(String text) throws IOException {
        //  FileWriter fw = new FileWriter("receipt.txt", true);//appends.
        //Did not want to append to the list of receipts. as they would all be added to the same file.
        //could have read from last value to only display most recent while keeping record of all transactions.

        PrintWriter pw = new PrintWriter("receipt.txt");
        pw.println(text);
        pw.close();
    }


    private void studentSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentSubTotalActionPerformed

    private void adultSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adultSubTotalActionPerformed

    private void studentQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentQtyActionPerformed
        studentSubTotal();//calculates and displays student sub total
    }//GEN-LAST:event_studentQtyActionPerformed

    private void adultQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultQtyActionPerformed
        adultSubTotal();//calculates and displays adult subtotal.
    }//GEN-LAST:event_adultQtyActionPerformed

    private void seniorQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorQtyActionPerformed
        seniorSubTotal();//calculates and displays senior sub total
    }//GEN-LAST:event_seniorQtyActionPerformed

    private void totalPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceTextFieldActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        
        
        String name = movName;
        String date = movDate;

        //get the type text labels.
        String stuType = studentLabel.getText();
        String adultType = adultLabel.getText();
        String seniorType = seniorLabel.getText();

        //get the quantity
        int stuQty = studentQty.getSelectedIndex();
        int aduQty = adultQty.getSelectedIndex();
        int senQty = seniorQty.getSelectedIndex();

        //get the total price for each
        String sTotal = studentSubTotal.getText();
        String aTotal = adultSubTotal.getText();
        String senTotal = seniorSubTotal.getText();

        //get the final price.
        String finalPrice = totalPriceTextField.getText();

        //prepare lines for printing to file
        String o1 = "Receipt";
        String o2 = "Movie: " + name;
        String o3 = "Date: " + date;
        String o4 = "Student Qty: " + stuQty + "x =" + sTotal;
        String o5 = "Adult Qty: " + aduQty + "x = " + aTotal;
        String o6 = "Senior Qty: " + senQty + "x = " + senTotal;
        String o7 = "TOTAL PRICE = " + finalPrice;

        //timestamp for receipt.
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        if(stuQty==0 && aduQty==0 && senQty==0){
            
            JOptionPane.showMessageDialog(null, "Please choose number of tickets.");
        }else{
            
        
        
        PrintWriter pw;//writing to a text file.
        try {
            pw = new PrintWriter("receipt.txt");
            pw.println(o1);
            pw.println(o2);
            pw.println(o3);
            pw.println(o4);
            pw.println(o5);
            pw.println(o6);
            pw.println(o7);
            pw.println("current time:");
            pw.println(timestamp);
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
        }

        String output = ("Purchase Details: "//unused. here for reference.
                + "\nMovie:\n" + name + "\nDate\n" + date
                + "\nStudent Qty: " + stuQty + "x = " + sTotal
                + "\nAdult Qty: " + aduQty + "x = " + aTotal
                + "\nSenior Qty: " + senQty + "x = " + senTotal
                + "\nTOTAL PRICE = " + finalPrice);

        JOptionPane.showMessageDialog(null,"Thank you for your purchase.\n Press receipt on the home page to view your receipt");
        dispose();
        Coursework c = new Coursework();
        }
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
        Coursework exit = new Coursework();
    }//GEN-LAST:event_btnExitActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        studentQty.setSelectedIndex(0);
        adultQty.setSelectedIndex(0);
        seniorQty.setSelectedIndex(0);
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel adultLabel;
    private javax.swing.JLabel adultPriceLabel;
    private javax.swing.JComboBox<String> adultQty;
    private javax.swing.JTextField adultSubTotal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel movieDataLabel;
    private javax.swing.JTextArea movieDetailsTF;
    private javax.swing.JPanel purchasePanel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel seniorLabel;
    private javax.swing.JLabel seniorPriceLabel;
    private javax.swing.JComboBox<String> seniorQty;
    private javax.swing.JTextField seniorSubTotal;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JLabel studentPriceLabel;
    private javax.swing.JComboBox<String> studentQty;
    private javax.swing.JTextField studentSubTotal;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalPriceTextField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
